config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :event_tickets
  resources :rooms
  resources :reviews
  get 'my_reviews', to: 'reviews#my_reviews'
  get 'all_reviews', to: 'reviews#all_reviews'
  resources :booking_histories
  root 'home#index'
  resources :attendees
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'attendees#new', as: 'signup'
  post 'signup', to: 'attendees#create', as: 'Register'
  get 'login', to: "sessions#new", as: 'login'
  # get 'logout', to: "sessions#destroy", as: 'logout'
  get '/search_attendees', to: 'attendees#search', as: 'search_attendees'
  delete 'logout', to: 'sessions#destroy', as: :logout
  delete 'account', to: 'attendees#destroy', as: 'delete_account'
  get 'rooms/:id/details', to: 'rooms#details', as: 'room_details'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  has_secure_password

  has_many :event_tickets, dependent: :destroy
  has_many :events, through: :event_tickets
  has_many :reviews, dependent: :destroy

  validates :email, presence: true, format: { with: /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\z/i }
  validates :phone_number, presence: true, format: { with: /\A\+1\d{10}\z/, message: "must be in the format +1 followed by 10 digits" }
  validates :credit_card_info, presence: true, length: { is: 16 }, numericality: { only_integer: true }
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: %i[ show edit update destroy ]
  before_action :require_admin, except: [:index]

  # GET /attendees or /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1 or /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
    # Prevent non-admin attendees from updating their ID
    unless current_user.is_admin
      redirect_to root_path, alert: "You are not authorized to perform this action." unless @attendee == current_user
    end
  end

  # POST /attendees or /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to root_path, notice: "Attendee was successfully created." }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1 or /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to attendee_url(@attendee), notice: "Attendee was successfully updated." }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1 or /attendees/1.json
  # def destroy
  #   EventTicket.where("attendee_id=?", @attendee.id ).limit(5000).delete_all
  #   Review.where("attendee_id=?", @attendee.id ).limit(5000).delete_all
  #
  #   # Only clear session if the current user is the attendee being destroyed and is not an admin
  #   if current_user == @attendee && !current_user.is_admin
  #     session[:user_id] = nil
  #   end
  #
  #   @attendee.destroy
  #
  #   respond_to do |format|
  #     format.html {
  #       if current_user && current_user.is_admin
  #         redirect_to attendees_url, notice: "Attendee was successfully destroyed."
  #       else
  #         redirect_to root_path, notice: "Account deleted successfully."
  #       end
  #     }
  #     format.json { head :no_content }
  #   end
  # end

  def destroy
    # Find all event tickets associated with the attendee being deleted
    event_tickets = EventTicket.where(attendee_id: @attendee.id)

    # Iterate over each event ticket to update the number of seats left for the associated event
    event_tickets.each do |event_ticket|
      event = event_ticket.event
      event.number_of_seats_left += event_ticket.number_of_tickets
      event.save
    end

    # Delete all associated event tickets and reviews
    EventTicket.where(attendee_id: @attendee.id).delete_all
    Review.where(attendee_id: @attendee.id).delete_all

    # Clear session if the current user is the attendee being destroyed and is not an admin
    if current_user == @attendee && !current_user.is_admin
      session[:user_id] = nil
    end

    # Destroy the attendee
    @attendee.destroy

    respond_to do |format|
      format.html do
        if current_user && current_user.is_admin
          redirect_to attendees_url, notice: "Attendee was successfully destroyed."
        else
          redirect_to root_path, notice: "Account deleted successfully."
        end
      end
      format.json { head :no_content }
    end
  end


  def search
    event_name = params[:event_name]
    @attendees = Attendee.joins(:event_tickets).joins(:events).where("events.name = ?", event_name).distinct
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_attendee
    @attendee = Attendee.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def attendee_params
    params.require(:attendee).permit(:email, :password, :name, :phone_number, :address, :credit_card_info, :is_admin)
  end

  def require_admin
    redirect_to root_path, alert: "You don't have permission to access this page." unless current_user && current_user.is_admin
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_attendee.html.erb
<table class="show-attendee-table" id="<%= dom_id(attendee) %>">
  <tbody>
  <tr>
    <td><strong>Email:</strong></td>
    <td><%= attendee.email %></td>
  </tr>
  <tr>
    <td><strong>Name:</strong></td>
    <td><%= attendee.name %></td>
  </tr>
  <tr>
    <td><strong>Phone number:</strong></td>
    <td><%= attendee.phone_number %></td>
  </tr>
  <tr>
    <td><strong>Address:</strong></td>
    <td><%= attendee.address %></td>
  </tr>
  <tr>
    <td><strong>Credit card info:</strong></td>
    <td><%= attendee.credit_card_info %></td>
  </tr>
  <tr>
    <td><strong>Is admin:</strong></td>
    <td><%= attendee.is_admin ? 'Yes' : 'No' %></td>
  </tr>
  </tbody>
</table>

app/views/attendees/_form.html.erb
<%= form_for @attendee, url: (@attendee.new_record? ? signup_path : attendee_path(@attendee)), method: (@attendee.new_record? ? :post : :patch) do |form| %>

<% if attendee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
        <% attendee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if attendee.is_admin %>
    <div>
      <strong>Email:</strong> <%= attendee.email %>
    </div>
  <% else %>
    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.text_field :email, pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$", title: "Please enter a valid email address" %>
    </div>

    <div>
      <%= form.label :password_digest, "Password", style: "display: block" %>
      <%= form.password_field :password %>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number, placeholder: "+1xxxxxxxxxx", pattern: "\+1\d{10}", title: "Please enter a phone number in the format +1 followed by 10 digits" %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :credit_card_info, style: "display: block" %>
    <%= form.text_field :credit_card_info, pattern: "[0-9]{16}", title: "Please enter a 16-digit credit card number" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  <%if current_user.nil? %>
    <%= link_to "Alread have an Account? Login", login_path %>
  <%end %>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing Profile</h1>

<%= render "form", attendee: @attendee %>

<br>

<div>
  <%= link_to "Show this attendee", @attendee %>
  <% if current_user.is_admin %>
    | <%= link_to "Back to attendees", attendees_path %>
  <% else %>
    <%= link_to "Back", root_path %>
  <% end %>
</div>

app/views/attendees/index.html.erb
<h1>Attendees</h1>
<%= form_with(url: search_attendees_path, method: "get") do %>
  <div>
    <%= label_tag :event_name, "Event Name:" %>
    <%= select_tag :event_name, options_for_select(Event.pluck(:name).uniq, params[:event_name]), include_blank: true %>
  </div>
  <div>
    <%= submit_tag "Search" %>
  </div>
<% end %>

<table class="table-bordered">
  <thead>
  <tr>
    <th class="cell-id">Id</th>
    <th class="cell-email">Email</th>
    <th class="cell-name">Name</th>
    <th class="cell-phone">Phone Number</th>
    <th class="cell-address">Address</th>
    <th class="cell-credit-info">Credit Card Info</th>
    <th class="cell-is-admin">Is Admin</th>
    <th class="cell-actions" colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @attendees.each do |attendee| %>
    <tr>
      <td class="cell-id"><%= attendee.id %></td>
      <td class="cell-email"><%= attendee.email %></td>
      <td class="cell-name"><%= attendee.name %></td>
      <td class="cell-phone"><%= attendee.phone_number %></td>
      <td class="cell-address"><%= attendee.address %></td>
      <td class="cell-credit-info"><%= attendee.credit_card_info %></td>
      <td class="cell-is-admin"><%= attendee.is_admin ? 'Yes' : 'No' %></td>
      <td class="cell-actions">
        <%= link_to "Show", attendee %> |


        <%= link_to "Edit", edit_attendee_path(attendee) %>

        <% if !attendee.is_admin %>
          | <%= link_to "Destroy", attendee, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New attendee", new_attendee_path %>
<br>
<%= link_to "Back", root_path%>

app/views/attendees/new.html.erb
<h1>New Attendee</h1>

<%= render "form", attendee: @attendee %><br>

<div>
  <% if current_user && current_user.is_admin %>
    <%= link_to "Back to attendees", attendees_path %>
  <% end %>
</div>

app/views/attendees/search.html.erb
<h2>Search Results</h2>

<% if @attendees.any? %>
  <table class="table-bordered">
    <thead>
    <tr>
      <th class="cell-id">Id</th>
      <th class="cell-email">Email</th>
      <th class="cell-name">Name</th>
      <th class="cell-phone">Phone Number</th>
      <th class="cell-address">Address</th>
      <th class="cell-credit-info">Credit Card Info</th>
      <th class="cell-is-admin">Is Admin</th>
      <th class="cell-actions">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td class="cell-id"><%= attendee.id %></td>
        <td class="cell-email"><%= attendee.email %></td>
        <td class="cell-name"><%= attendee.name %></td>
        <td class="cell-phone"><%= attendee.phone_number %></td>
        <td class="cell-address"><%= attendee.address %></td>
        <td class="cell-credit-info"><%= attendee.credit_card_info %></td>
        <td class="cell-is-admin"><%= attendee.is_admin ? 'Yes' : 'No' %></td>
        <td class="cell-actions"><%= link_to "Show", attendee %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No attendees found for the specified event.</p>
<% end %>
<%= link_to "Back", attendees_path %>

app/views/attendees/show.html.erb
<%= render @attendee %>
<div>
  <%= link_to "Back to attendees", attendees_path(:attendee_id => current_user.id) %>
</div>