config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :event_tickets
  resources :rooms
  resources :reviews
  get 'my_reviews', to: 'reviews#my_reviews'
  get 'all_reviews', to: 'reviews#all_reviews'
  resources :booking_histories
  root 'home#index'
  resources :attendees
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'attendees#new', as: 'signup'
  post 'signup', to: 'attendees#create', as: 'Register'
  get 'login', to: "sessions#new", as: 'login'
  # get 'logout', to: "sessions#destroy", as: 'logout'
  get '/search_attendees', to: 'attendees#search', as: 'search_attendees'
  delete 'logout', to: 'sessions#destroy', as: :logout
  delete 'account', to: 'attendees#destroy', as: 'delete_account'
  get 'rooms/:id/details', to: 'rooms#details', as: 'room_details'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  has_secure_password

  has_many :event_tickets, dependent: :destroy
  has_many :events, through: :event_tickets
  has_many :reviews, dependent: :destroy

  validates :email, presence: true, format: { with: /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\z/i }
  validates :phone_number, presence: true, format: { with: /\A\+1\d{10}\z/, message: "must be in the format +1 followed by 10 digits" }
  validates :credit_card_info, presence: true, length: { is: 16 }, numericality: { only_integer: true }
end

app/models/booking_history.rb
class BookingHistory < ApplicationRecord
  belongs_to :event
  belongs_to :attendee
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :room
  has_many :event_tickets, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validate :no_overlapping_events
  validate :start_time_must_be_in_future

  def start_time_must_be_in_future
    event_start_datetime = DateTime.parse("#{date} #{start_time.strftime('%H:%M:%S')}")
    event_end_datetime = DateTime.parse("#{date} #{end_time.strftime('%H:%M:%S')}")
    current_time=DateTime.parse("#{date} #{Time.current.strftime('%H:%M:%S')}")
    return if start_time.blank? || date.blank?
    if(date<Date.current)
      errors.add(:date, "must be in the future")
    elsif(event_start_datetime<current_time && date == Date.current)
      errors.add(:start_time, "must be in the future. Current start time : #{start_time}, but now it's : #{Time.current}")
    elsif(event_start_datetime>event_end_datetime)
      errors.add(:start_time, "must be less than end time")
    end
  end


  validates :ticket_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :number_of_seats_left, presence: true, numericality: { greater_than_or_equal_to: 0 }





  def decrease_seats_left
    self.number_of_seats_left -= 1
    save
  end

  def increase_seats_left
    self.number_of_seats_left += 1
    save
  end

  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :not_sold_out, -> { where('number_of_seats_left > 0') }


  def no_overlapping_events
    return unless room && date && start_time && end_time

    # Convert 'date' and 'time' attributes to full DateTime objects for the event being validated
    event_start_datetime = DateTime.parse("#{date} #{start_time.strftime('%H:%M:%S')}")
    event_end_datetime = DateTime.parse("#{date} #{end_time.strftime('%H:%M:%S')}")

    overlapping_events = room.events.where.not(id: id).select do |e|
      # Convert each event's 'date' and 'time' attributes to full DateTime objects
      e_start_datetime = DateTime.parse("#{e.date} #{e.start_time.strftime('%H:%M:%S')}")
      e_end_datetime = DateTime.parse("#{e.date} #{e.end_time.strftime('%H:%M:%S')}")

      # Check if the current event overlaps with existing events
      (event_start_datetime...event_end_datetime).overlaps?(e_start_datetime...e_end_datetime)
    end

    errors.add(:base, "There is already an event scheduled in this room during the selected time slot.") if overlapping_events.any?
  end

end

app/models/event_ticket.rb
class EventTicket < ApplicationRecord
  belongs_to :attendee
  belongs_to :event
  belongs_to :buyer, class_name: 'Attendee', foreign_key: 'buyer_id', optional: true

  def attendee_name
    attendee.name
  end

  def event_name
    event.name
  end
  before_create :generate_confirmation_number

  private

  def generate_confirmation_number
    loop do
      random_number = SecureRandom.hex(6).upcase
      unless self.class.exists?(confirmation_number: random_number)
        self.confirmation_number = random_number
        break
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :attendee
  belongs_to :event

  validates :rating, numericality: { less_than_or_equal_to: 5, message: "must be 5 or below" }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :events

  def self.available_rooms(date, start_time, end_time)
    start_datetime = DateTime.parse("#{date} #{start_time}")
    end_datetime = DateTime.parse("#{date} #{end_time}")

    booked_room_ids = Event.where("start_time < ? AND end_time > ?", end_datetime, start_datetime).pluck(:room_id)
    where.not(id: booked_room_ids)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :credit_card
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :credit_cards
  has_many :transactions
  validates :email_address, presence: true, uniqueness: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!--<p id=”notice”><%#= notice %></p>-->
<h1>Wolf Events</h1>
<h3>Event Management System</h3>
<% if current_user && current_user.is_admin %>
  Logged in as <%= current_user.name %>.<br><br>
  <%= link_to "All Events", events_path %><br>
  <%= link_to "All Attendees", attendees_path %><br>
  <%= link_to "All Event Tickets", event_tickets_path %><br>
  <%= link_to "Booking History", event_tickets_path(:attendee_id => current_user.id) %><br>
  <%= link_to "All Rooms", rooms_path %><br>
  <%= link_to "My Reviews", my_reviews_path %><br>
  <%= link_to "All Reviews", reviews_path %><br>
  <%= link_to "Edit Profile", edit_attendee_path(current_user) %><br><br>
  <%#= link_to "Logout", logout_path %>
  <%= form_tag logout_path, method: :delete do %>
    <%= submit_tag "Logout", style: "background-color: blue; color: white;" %>
  <% end %>
<% elsif current_user && !current_user.is_admin %>
  Logged in as <%= current_user.name %>.<br><br>
  <%= link_to "All Events", events_path %><br>
  <%= link_to "Booking History", event_tickets_path(:attendee_id => current_user.id) %><br>
  <%= link_to "My Reviews", my_reviews_path %><br>
  <%= link_to "All Reviews", reviews_path %><br>
  <%= link_to "Edit Profile", edit_attendee_path(current_user) %><br>
  <%= link_to "Delete Account", attendee_path(current_user), method: :delete, data: { confirm: "Are you sure you want to delete your account?" } %>

  <br><br>
  <%= form_tag logout_path, method: :delete do %>
    <%= submit_tag "Logout", style: "background-color: blue; color: white;" %>
  <% end %>
<% else %>
  <%= link_to "Login", login_path %> or
  <%= link_to "Register", signup_path %>
<% end %>