config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :event_tickets
  resources :rooms
  resources :reviews
  get 'my_reviews', to: 'reviews#my_reviews'
  get 'all_reviews', to: 'reviews#all_reviews'
  resources :booking_histories
  root 'home#index'
  resources :attendees
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'attendees#new', as: 'signup'
  post 'signup', to: 'attendees#create', as: 'Register'
  get 'login', to: "sessions#new", as: 'login'
  # get 'logout', to: "sessions#destroy", as: 'logout'
  get '/search_attendees', to: 'attendees#search', as: 'search_attendees'
  delete 'logout', to: 'sessions#destroy', as: :logout
  delete 'account', to: 'attendees#destroy', as: 'delete_account'
  get 'rooms/:id/details', to: 'rooms#details', as: 'room_details'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event_ticket.rb
class EventTicket < ApplicationRecord
  belongs_to :attendee
  belongs_to :event
  belongs_to :buyer, class_name: 'Attendee', foreign_key: 'buyer_id', optional: true

  def attendee_name
    attendee.name
  end

  def event_name
    event.name
  end
  before_create :generate_confirmation_number

  private

  def generate_confirmation_number
    loop do
      random_number = SecureRandom.hex(6).upcase
      unless self.class.exists?(confirmation_number: random_number)
        self.confirmation_number = random_number
        break
      end
    end
  end
end

app/controllers/event_tickets_controller.rb
class EventTicketsController < ApplicationController
  before_action :set_event_ticket, only: %i[ show edit update destroy ]

  def index
    @event_tickets = current_user.is_admin ? EventTicket.all : EventTicket.where("attendee_id = ? OR buyer_id = ?", current_user.id, current_user.id)
  end
  def show
    @event_ticket = EventTicket.find(params[:id])
    if !current_user.is_admin && current_user != @event_ticket.attendee
      redirect_to root_path, alert: "You are not authorized to view this event ticket."
    end
  end

  def new
    @event = Event.find_by_id(event_ticket_params[:event_id])
    params[:event_ticket][:total_cost] = params[:event_ticket][:number_of_tickets].to_i * @event.ticket_price
    @event_ticket = EventTicket.new(event_ticket_params)
  end

  def event_ticket_params
    params.require(:event_ticket).permit(:attendee_id, :event_id, :confirmation_number, :number_of_tickets, :total_cost, :buyer_id)
  end

  def edit
  end

  def create
    @event = Event.find_by_id(event_ticket_params[:event_id])
    params[:event_ticket][:total_cost] = params[:event_ticket][:number_of_tickets].to_i * @event.ticket_price
    @event_ticket = EventTicket.new(event_ticket_params)


    respond_to do |format|
      if @event.number_of_seats_left >= @event_ticket.number_of_tickets and @event_ticket.save
        @event.number_of_seats_left = @event.number_of_seats_left - @event_ticket.number_of_tickets
        @event.save
        format.html { redirect_to event_ticket_url(@event_ticket), notice: "Event ticket was successfully created." }
        format.json { render :show, status: :created, location: @event_ticket }
      elsif @event.number_of_seats_left < @event_ticket.number_of_tickets
        format.html { redirect_to events_url, notice: "Not enough seats left (Seats left: "+@event.number_of_seats_left.to_s+")" }
        format.json { render json: @event_ticket.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to event_ticket_url(@event_ticket), notice: "Booking unsuccessful" }
        format.json { render json: @event_ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      old_number_of_tickets = @event_ticket.number_of_tickets
      new_number_of_tickets = event_ticket_params[:number_of_tickets].to_i

      if @event_ticket.update(event_ticket_params)
        @event = @event_ticket.event
        difference_in_tickets = old_number_of_tickets - new_number_of_tickets

        if difference_in_tickets > 0
          @event.number_of_seats_left += difference_in_tickets
        elsif difference_in_tickets < 0 && @event.number_of_seats_left >= difference_in_tickets.abs
          @event.number_of_seats_left -= difference_in_tickets.abs
        else
          format.html { redirect_to event_ticket_url(@event_ticket), notice: "Not enough seats left." }
          format.json { render json: @event_ticket.errors, status: :unprocessable_entity }
          return
        end

        @event.save

        format.html { redirect_to event_ticket_url(@event_ticket), notice: "Event ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @event_ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_ticket.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @event_ticket = EventTicket.find(params[:id])
    @event = @event_ticket.event

    respond_to do |format|
      if @event_ticket.destroy
        @event.number_of_seats_left += @event_ticket.number_of_tickets
        @event.save
        format.html { redirect_to events_url, notice: "Event ticket was successfully canceled." }
        format.json { head :no_content }
      else
        format.html { redirect_to event_ticket_url(@event_ticket), notice: "Cancellation unsuccessful." }
        format.json { render json: @event_ticket.errors, status: :unprocessable_entity }
      end
    end
  end



  private
  def set_event_ticket
    @event_ticket = EventTicket.find(params[:id])
  end

  def require_admin
    unless current_user && current_user.is_admin
      redirect_to root_path, alert: "You are not authorized to view all tickets."
    end
  end
end

app/helpers/event_tickets_helper.rb
module EventTicketsHelper
end

app/views/event_tickets/_event_ticket.html.erb
<div id="<%= dom_id event_ticket %>">
  <p>
    <strong>Attendee:</strong>
    <%= event_ticket.attendee_name %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= event_ticket.event_name %>
  </p>

  <p>
    <strong>Number of Tickets:</strong>
    <%= event_ticket.number_of_tickets %>
  </p>

  <p>
    <strong>Total Cost:</strong>
    <%= event_ticket.total_cost %>
  </p>

  <p>
    <strong>Confirmation number:</strong>
    <%= event_ticket.confirmation_number %>
  </p>

</div>

app/views/event_tickets/_form.html.erb
<%= form_with(model: event_ticket) do |form| %>
  <% if event_ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event_ticket.errors.count, "error") %> prohibited this event_ticket from being saved:</h2>

      <ul>
        <% event_ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :attendee_id, style: "display: none" %>
    <%= form.text_field :attendee_id, style: "display: none" %>
  </div>

  <div>
    <%= form.label :event_id, style: "display: none" %>
    <%= form.text_field :event_id, style: "display: none", id: "event_id"  %>
  </div>

  <div>
    <%= form.label :number_of_tickets, style: "display: block" %>
    <%= form.number_field :number_of_tickets, id: "number_of_tickets", value: 1, min: 1 %>
  </div>

  <div>
    <%= form.label :total_cost, style: "display: block" %>
    <%= form.text_field :total_cost, readonly: true, id: "total_cost", value: @event_ticket.event.ticket_price.to_d %>
  </div>

  <div>
    <%= form.label :buyer_id , "Ticket Recipient"%>
    <%= form.collection_select :buyer_id, Attendee.all, :id, :name, { prompt: "Select a User" } %>
  </div>


  <script>
      var numberField = document.getElementById('number_of_tickets');
      var totalField = document.getElementById('total_cost');
      var ticketCost = <%= @event_ticket.event.ticket_price.to_d %>;

      numberField.addEventListener('input', function() {
          var numberOfTickets = parseFloat(numberField.value);
          var totalCost = numberOfTickets * ticketCost;
          totalField.value = totalCost.toFixed(2); // Assuming you want to display the total with two decimal places
      });
  </script>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/event_tickets/edit.html.erb
<h1>Editing Event Ticket</h1>

<%= form_for @event_ticket do |form| %>
  <div>
    <%= form.label :attendee_id, style: "display: none" %>
    <%= form.text_field :attendee_id, style: "display: none" %>
  </div>

  <div>
    <%= form.label :event_id, style: "display: none" %>
    <%= form.text_field :event_id, style: "display: none", id: "event_id"  %>
  </div>

  <div>
    <%= form.label :number_of_tickets, style: "display: block" %>
    <%= form.text_field :number_of_tickets, id: "number_of_tickets", value: @event_ticket.number_of_tickets || 1 %>
  </div>

  <div>
    <%= form.label :total_cost, style: "display: block" %>
    <%= form.text_field :total_cost, readonly: true, id: "total_cost", value: @event_ticket.total_cost.to_d %>
  </div>

  <script>
      var numberField = document.getElementById('number_of_tickets');
      var totalField = document.getElementById('total_cost');
      var ticketCost = <%= @event_ticket.event.ticket_price.to_d %>;

      numberField.addEventListener('input', function() {
          var numberOfTickets = parseFloat(numberField.value);
          var totalCost = numberOfTickets * ticketCost;
          totalField.value = totalCost.toFixed(2); // Assuming you want to display the total with two decimal places
      });
  </script>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Show this event ticket", @event_ticket %> |
  <%= link_to "Back to event tickets", event_tickets_path(attendee_id: current_user.id) %>
</div>

app/views/event_tickets/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Event Tickets</h1>
<% if @event_tickets.any? %>
  <table class="eventTicket-table">
    <thead>
    <tr>
      <th>Bought By</th>
      <th>Event Name</th>
      <th>Date</th>
      <th>Room</th>
      <th>Number Of Tickets</th>
      <th>Confirmation Number</th>
      <th>Bought For</th>
      <th colspan="2">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @event_tickets.each do |event_ticket| %>
      <tr>
        <td><%= event_ticket.attendee_name %></td>
        <td><%= event_ticket.event_name %></td>
        <td><%= event_ticket.event.date.strftime('%Y-%m-%d') if event_ticket.event.date %></td>
        <td><%=event_ticket.event.room.location %></td>
        <td><%= event_ticket.number_of_tickets %></td>
        <td><%= event_ticket.confirmation_number %></td>
        <td><%= event_ticket.buyer&.name || "N/A" %></td>
        <td>
          <%= link_to "Show", event_ticket %> |
          <% current_time = DateTime.parse("#{event_ticket.event.date} #{Time.current.strftime('%H:%M:%S')}") %>
          <% event_end_time = DateTime.parse("#{event_ticket.event.date} #{event_ticket.event.end_time.strftime('%H:%M:%S')}") %>
          <% if current_user && current_user.is_admin %>
            <%= link_to "Edit", edit_event_ticket_path(event_ticket) %> |
            <%= link_to "Destroy", event_ticket, method: :delete, data: { confirm: 'Are you sure?' } %> |
          <% elsif current_user && !current_user.is_admin && current_user.id == event_ticket.attendee_id %>
            <%= link_to "Edit", edit_event_ticket_path(event_ticket) %> |
            <%= link_to "Cancel Ticket(s)", event_ticket, method: :delete, data: { confirm: 'Are you sure?' } %> |
          <% end %>

          <% if event_ticket.event.category.in?(['Miscellaneous', 'Private']) || event_ticket.event.date > Date.current %>
            <%= link_to "Write Review", "#", class: "disabled-link", disabled: "disabled", onclick: "return false;", aria_disabled: "true", style: "color: #ccc; cursor: not-allowed; pointer-events: none;" %>
          <% elsif event_end_time < current_time && event_ticket.event.date == Date.current %>
            <% if current_user && current_user.is_admin? || current_user && current_user.id == event_ticket.attendee_id %>
              <%= link_to "Write Review", new_review_path(event_id: event_ticket.event_id) %>
            <% else %>
              <%= link_to "Write Review", "#", class: "disabled-link", disabled: "disabled", onclick: "return false;", aria_disabled: "true", style: "color: #ccc; cursor: not-allowed; pointer-events: none;" %>
            <% end %>
          <% else %>
            <%= link_to "Write Review", new_review_path(event_id: event_ticket.event_id) %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No Tickets as of now</p>
<% end %>

<%= link_to "New event ticket", events_path %>
<br>
<%= link_to "Back", root_path %>

app/views/event_tickets/new.html.erb
<h1>New Event Ticket</h1>

<%= render "form", event_ticket: @event_ticket %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/event_tickets/show.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<%= render @event_ticket %>

<div>

  <% if current_user && current_user.is_admin %>
    <%= link_to "Back to all events", events_path %> |
    <%= link_to "Booking History", event_tickets_path(:attendee_id => current_user.id) %> |
    <%= link_to "Back to event tickets", event_tickets_path %>
  <% end %>

<% if current_user && !current_user.is_admin %>
    <%= link_to "Back to all events", events_path %> |
    <%= link_to "Booking History", event_tickets_path(:attendee_id => current_user.id) %> |
  <% end %>
</div>